### ISSUE TITLE
`hoistError'` and `hoistErrorM'`

### ISSUE THREAD

**Issue by lrworth** [alephcloud/hs-hoist-error#11]
`Control.Monad.Fail.Hoist` provides `hoistFail' = hoistFail id` and `hoistFailM' = hoistFailM id`.

`Control.Monad.Error.Hoist` should provide `hoistError' = hoistError id` and `hoistErrorM' = hoistErrorM id`.

**Comment by endgame** [comment]
You might need to close this manually - it seems GH won't respect cross-repo "closes" in commit messages.

**Comment by lrworth** [comment]
Fixed by https://github.com/qfpl/hs-hoist-error/pull/11
